#!/usr/bin/env python3
"""
recorder.py - Interactive touch and test flow recorder.
Allows recording steps interactively with real-time UI element mapping and exporting
as reusable automated test scenarios (JSON or Python).
"""

import json
import os
import sys
import time
from typing import Any, Dict, List, Optional

from .actions import ActionEngine
from .core import AdbDevice
from .mapper import ScreenMap, UiElement


class FlowRecorder:
    def __init__(self, output_file: str, device: Optional[AdbDevice] = None):
        self.output_file = output_file
        self.device = device or AdbDevice()
        self.actions = ActionEngine(self.device)
        self.steps: List[Dict[str, Any]] = []

    def add_step(self, action_type: str, **kwargs):
        step = {
            "step": len(self.steps) + 1,
            "action": action_type,
            "timestamp": round(time.time(), 2),
            **kwargs,
        }
        self.steps.append(step)
        print(f"Recorded Step #{step['step']}: {action_type} {kwargs}")

    def save(self):
        os.makedirs(os.path.dirname(os.path.abspath(self.output_file)), exist_ok=True)
        data = {
            "name": os.path.basename(self.output_file).replace(".json", ""),
            "device": self.device.serial,
            "screen_size": list(self.device.get_screen_size()),
            "total_steps": len(self.steps),
            "steps": self.steps,
        }
        with open(self.output_file, "w") as f:
            json.dump(data, f, indent=2)
        print(f"Flow saved to: {self.output_file}")

    def export_python_script(self, py_path: str):
        os.makedirs(os.path.dirname(os.path.abspath(py_path)), exist_ok=True)
        lines = [
            "#!/usr/bin/env python3",
            '"""Automated test script generated by App Use Recorder."""',
            "from tools.app_use.actions import ActionEngine",
            "import time",
            "",
            "def run_test():",
            "    app = ActionEngine()",
            "    print('Starting automated test run...')",
            "",
        ]
        for s in self.steps:
            act = s["action"]
            if act == "tap":
                target = s.get("target")
                lbl = s.get("label", "")
                lines.append(f"    # Step {s['step']}: Tap {lbl}")
                lines.append(f"    app.tap({repr(target)})")
                lines.append("    time.sleep(0.5)")
            elif act == "type":
                target = s.get("target")
                text = s.get("text", "")
                lines.append(f"    # Step {s['step']}: Type into {target}")
                lines.append(f"    app.type_text({repr(target)}, {repr(text)})")
                lines.append("    time.sleep(0.5)")
            elif act == "swipe":
                direction = s.get("direction", "up")
                lines.append(f"    # Step {s['step']}: Swipe {direction}")
                lines.append(f"    app.swipe({repr(direction)})")
                lines.append("    time.sleep(0.5)")
            elif act == "key":
                keycode = s.get("keycode", "BACK")
                lines.append(f"    # Step {s['step']}: Key {keycode}")
                lines.append(f"    app.key({repr(keycode)})")
                lines.append("    time.sleep(0.5)")
            elif act == "assert_text":
                txt = s.get("text", "")
                lines.append(f"    # Step {s['step']}: Assert text {repr(txt)}")
                lines.append(f"    app.assert_text({repr(txt)})")
            elif act == "wait":
                sec = s.get("seconds", 1.0)
                lines.append(f"    app.wait({sec})")

        lines.extend([
            "",
            "    print('Test completed successfully!')",
            "",
            "if __name__ == '__main__':",
            "    run_test()",
        ])

        with open(py_path, "w") as f:
            f.write("\n".join(lines) + "\n")
        os.chmod(py_path, 0o755)
        print(f"Python script exported to: {py_path}")

    def interactive_session(self):
        print("=" * 60)
        print("  APP USE INTERACTIVE RECORDER")
        print("=" * 60)
        print("Commands:")
        print("  map                     - Inspect all touchable elements on current screen")
        print("  tap <target|#id|coords> - Tap element and record")
        print("  type <target> <text>    - Type text into input element and record")
        print("  swipe <up|down|l|r>     - Swipe gesture and record")
        print("  key <BACK|HOME|ENTER>   - Send hardware key and record")
        print("  assert <text>           - Add text assertion step")
        print("  wait <seconds>          - Add sleep delay")
        print("  undo                    - Remove last recorded step")
        print("  show                    - Show recorded steps so far")
        print("  save                    - Save and exit")
        print("  exit / quit             - Exit without saving")
        print("=" * 60)

        while True:
            try:
                line = input("\nrecord > ").strip()
            except (EOFError, KeyboardInterrupt):
                break

            if not line:
                continue

            parts = line.split(maxsplit=1)
            cmd = parts[0].lower()
            arg = parts[1].strip() if len(parts) > 1 else ""

            if cmd in ("exit", "quit"):
                print("Exiting recorder.")
                break

            elif cmd == "save":
                self.save()
                if self.output_file.endswith(".json"):
                    py_file = self.output_file.replace(".json", ".py")
                    self.export_python_script(py_file)
                break

            elif cmd == "show":
                print(f"Recorded {len(self.steps)} steps:")
                for s in self.steps:
                    print(f"  #{s['step']} {s['action']}: {s}")

            elif cmd == "undo":
                if self.steps:
                    popped = self.steps.pop()
                    print(f"Removed Step #{popped['step']}: {popped['action']}")
                else:
                    print("No steps to undo.")

            elif cmd == "map":
                smap = self.actions.get_screen_map()
                print(smap.to_table())

            elif cmd == "tap":
                if not arg:
                    print("Usage: tap <target | #id | 'Button Label' | x y>")
                    continue
                try:
                    el = self.actions.tap(arg)
                    self.add_step(
                        "tap",
                        target=el.slug if el.slug else arg,
                        label=el.label or arg,
                        center=list(el.center),
                        bounds=list(el.bounds),
                    )
                except Exception as e:
                    print(f"Error tapping '{arg}': {e}")

            elif cmd == "type":
                # Syntax: type <target> <text> or type "Search" "Aspirin"
                # Parse target and text
                type_parts = arg.split(maxsplit=1)
                if len(type_parts) < 2:
                    print("Usage: type <target> <text>")
                    continue
                tgt, txt = type_parts[0], type_parts[1]
                try:
                    self.actions.type_text(tgt, txt)
                    self.add_step("type", target=tgt, text=txt)
                except Exception as e:
                    print(f"Error typing into '{tgt}': {e}")

            elif cmd in ("swipe", "scroll"):
                direction = arg or "up"
                try:
                    self.actions.swipe(direction)
                    self.add_step("swipe", direction=direction)
                except Exception as e:
                    print(f"Error swiping '{direction}': {e}")

            elif cmd == "key":
                k = arg.upper() or "BACK"
                try:
                    self.actions.key(k)
                    self.add_step("key", keycode=k)
                except Exception as e:
                    print(f"Error sending key '{k}': {e}")

            elif cmd == "assert":
                if not arg:
                    print("Usage: assert <expected text>")
                    continue
                try:
                    self.actions.assert_text(arg, timeout=2.0)
                    self.add_step("assert_text", text=arg)
                    print(f"Assertion passed: '{arg}' is visible.")
                except Exception as e:
                    print(f"Assertion failed: {e}")

            elif cmd == "wait":
                sec = float(arg) if arg else 1.0
                self.actions.wait(sec)
                self.add_step("wait", seconds=sec)

            else:
                print(f"Unknown command: '{cmd}'. Type 'map', 'tap', 'type', 'swipe', 'key', 'assert', 'save', or 'exit'.")
